version: "3.9"
services:
  database:
    image: postgres
    restart: always
    ports:
      - 127.0.0.1::5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB1=${DB_NAME}
      - POSTGRES_DB2=${DB_NAME_TEST}
    volumes:
      - pgdata:/data/postgres
      - ./docker/postgres:/docker-entrypoint-initdb.d
volumes:
  pgdata:
    driver: local    
